import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
         <ul className="h-13 flex gap-25 text-amber-50 ml-130 mt-5" >
    <li ><Link href={`/`}>HOME</Link></li>
    <li ><Link href={`/about`}>ABOUT</Link></li>
<li ><Link href={`/products`}>PRODUCTS</Link></li>
<li ><Link href={`/ourteam`}>OUR TEAM</Link></li>
<li ><Link href={`/contacts`}>CONTACTS</Link></li>
    
  </ul>
        {children}
      </body>
    </html>
  );
}
